---
- name: This is a play within a playbook
  hosts: windows
  vars:
    iis_sites:
      - name: 'Ansible Playbook Test'
        port: '8080'
        path: 'C:\sites\playbooktest'
      - name: 'Ansible Playbook Test 2'
        port: '8081'
        path: 'C:\sites\playbooktest2'
    iis_test_message: "Hello World!  My test IIS Server"
  handlers:
    - name: Restart IIS service
      listen: restart_iis_service_handler
      ansible.windows.win_service:
        name: W3Svc
        state: restarted
        start_mode: auto
  tasks:
