# MkDocs configuration file
site_name: Ansible Workshop - Windows Automation
copyright: Copyright &copy; Computacenter 2025
extra_css:
  - assets/stylesheets/tables.css
extra_javascript:
  - assets/javascripts/extra/refresh-on-toggle-dark-light.js
  - assets/javascripts/extra/tablesort.min.js
  - assets/javascripts/extra/tablesort.js
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path:
        - .
        - docs/windows-automation/snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
plugins:
  - search:
      lang: en
      separator: '[\s]'
  - autolinks:
  - git-revision-date-localized:
    # This plugin needs a Git executable and the .git folder
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]
      fallback_to_build_date: true
      locale: en
  - print-site:
    # This plugin should always defined as the last one
      add_cover_page: true
      add_print_site_banner: true
      cover_page_template: "docs/assets/pdf/cover-page.tpl"
      enabled: !ENV [ENABLED_PRINT_SITE, True]
      print_page_title: ""
      print_site_banner_template: "docs/assets/pdf/print-banner.tpl"
theme:
  name: material
  custom_dir: docs/assets/overrides
  icon:
    repo: fontawesome/brands/github
    admonition:
      example: octicons/terminal-24
  logo: assets/images/ansible-logo-black.png
  language: en
  favicon: assets/images/ansible-logo-black.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/TimGrt/ansible-windows-workshop
repo_name: timgrt/ansible-windows-workshop
# Navigation definition
nav:
  - "Workshop Overview":
      - index.md
      - preparation.md
  - "Exercises":
    - windows-automation/windows-adhoc.md
    - windows-automation/windows-playbook.md
    - windows-automation/windows-project.md
    - windows-automation/windows-advanced-playbooks.md
    - windows-automation/windows-roles.md
    - windows-automation/windows-patch.md
